### ISSUE TITLE
how to fuzz other programs except for the busybox and solve the "no route to host" problems

### ISSUE THREAD

**Issue by buptsseGJ** [zyw-200/FirmAFL#22]
Hi, you have implemented a meaningful tool. Recently, I'm trying to use your tool. But I met the following two problems and looked forward to your help.

1. I want to fuzz other binaries except for the busybox. **With reference to the commands that have been commented out in FirmAFL_config, I changed the user.sh file to contain the following contents:**
```
#DIR-815_FIRMWARE_1.01 firmware
AFL="./afl-fuzz -m none -t 800000+ -Q -i ./inputs -o ./outputs -x keywords"
chroot . \
${AFL} \
/htdocs/web/hedwig.cgi
````
But it reported that `[-] PROGRAM ABORT : No instrumentation detected.
 Location : perform_dry_run(), afl-fuzz.c:2874`
During the fuzzing process,  I don't use the 9050 image_id identifier for the DIR-815_FIRMWARE_1.01 firmware as shown in the readme, but an arbitrary directory named "image_4". I don't know if this will affect.
```
mapping_filename=../image_4/mapping_table
init_read_pipename=../image_4/user_cpu_state
write_pipename=../image_4/full_cpu_state
start_fork_pc=0x4023e0
program_analysis=hedwig.cgi
lib_name=libuClibc-0.9.30.1.so
environ_offset=0x72bf0
feed_type=FEED_ENV
id=4
opti=yes
```
**So, how can I fuzz other programs except for the busybox? Is it because the cgi file is special?** 

2. For the DIR-815_FIRMWARE_1.01 firmware, I run the command `sudo python start.py 4` for the busybox binary. It worked well. But if I executed the `python test.py` alone outside the start.py, it reported that 
```
[+] sending buffer size 3158
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    s.connect(("192.168.0.1", 80))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 113] No route to host
```
**So, does test.py need to be executed before executing the user.sh file?**

Thank you.

**Comment by amlamarra** [comment]
I, too, am wondering how to fuzz other programs. But you should probably create 2 separate issues for these.
