### ISSUE TITLE
Fork server handshake failed

### ISSUE THREAD

**Issue by pureGavin** [zyw-200/FirmAFL#43]
i do "python start.py 105568" but failed 
Could not create fifo ../image_9050/user_cpu_state
[+] sending buffer size 3158
./afl-fuzz -m none -t 800000+ -Q -i ./inputs -o ./outputs -x keywords
afl-fuzz 2.52b by <lcamtuf@google.com>
[+] You have 1 CPU core and 0 runnable tasks (utilization: 0%).
[*] Setting up output directories...
[*] Scanning './inputs'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Loading extra dictionary from 'keywords' (level 0)...
[+] Loaded 115 extra tokens, size range 4 B to 126 B.
[!] WARNING: Some tokens are relatively large (126 B) - consider trimming.
[*] Validating target binary...
[*] Attempting dry run with 'id:000000,orig:seed'...
dry run:./outputs/queue/id:000000,orig:seed
[*] Spinning up the fork server...

[-] Hmm, looks like the target binary terminated before we could complete a
    handshake with the injected code. Perhaps there is a horrible bug in the
    fuzzer. Poke <lcamtuf@coredump.cx> for troubleshooting tips.

[-] PROGRAM ABORT : Fork server handshake failed
         Location : init_forkserver(), afl-fuzz.c:2253

what should i do?

**Comment by pureGavin** [comment]
i use DIR645, it's same with DIR815 and the vuln is in cgibin

**Comment by pureGavin** [comment]
there is an error when i try DIR815 and run start.py 
[+] sending buffer size 3158
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    s.connect(("192.168.0.1", 80))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 113] No route to host
./afl-fuzz -m none -t 800000+ -Q -i ./inputs -o ./outputs -x keywords
afl-fuzz 2.52b by <lcamtuf@google.com>
[+] You have 1 CPU core and 0 runnable tasks (utilization: 0%).
[*] Setting up output directories...
[*] Scanning './inputs'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Loading extra dictionary from 'keywords' (level 0)...
[+] Loaded 115 extra tokens, size range 4 B to 126 B.
[!] WARNING: Some tokens are relatively large (126 B) - consider trimming.
[*] Validating target binary...
[*] Attempting dry run with 'id:000000,orig:seed'...
dry run:./outputs/queue/id:000000,orig:seed
[*] Spinning up the fork server...

[-] Whoops, the target binary crashed suddenly, before receiving any input
    from the fuzzer! There are several probable explanations:

    - The binary is just buggy and explodes entirely on its own. If so, you
      need to fix the underlying problem or find a better replacement.

    - Less likely, there is a horrible bug in the fuzzer. If other options
      fail, poke <lcamtuf@coredump.cx> for troubleshooting tips.

[-] PROGRAM ABORT : Fork server crashed with signal 6
         Location : init_forkserver(), afl-fuzz.c:2201

looks like IP address problem... still don't know what should i do...

**Comment by gy-cmykl** [comment]
> i do "python start.py 105568" but failed
> Could not create fifo ../image_9050/user_cpu_state
> [+] sending buffer size 3158
> ./afl-fuzz -m none -t 800000+ -Q -i ./inputs -o ./outputs -x keywords
> afl-fuzz 2.52b by [lcamtuf@google.com](mailto:lcamtuf@google.com)
> [+] You have 1 CPU core and 0 runnable tasks (utilization: 0%).
> [_] Setting up output directories... [_] Scanning './inputs'...
> [+] No auto-generated dictionary tokens to reuse.
> [_] Creating hard links for all input files... [_] Loading extra dictionary from 'keywords' (level 0)...
> [+] Loaded 115 extra tokens, size range 4 B to 126 B.
> [!] WARNING: Some tokens are relatively large (126 B) - consider trimming.
> [_] Validating target binary... [_] Attempting dry run with 'id:000000,orig:seed'...
> dry run:./outputs/queue/id:000000,orig:seed
> [*] Spinning up the fork server...
> 
> [-] Hmm, looks like the target binary terminated before we could complete a
> handshake with the injected code. Perhaps there is a horrible bug in the
> fuzzer. Poke [lcamtuf@coredump.cx](mailto:lcamtuf@coredump.cx) for troubleshooting tips.
> 
> [-] PROGRAM ABORT : Fork server handshake failed
> Location : init_forkserver(), afl-fuzz.c:2253
> 
> what should i do?

I have the same problem. Have you solved it

**Comment by pureGavin** [comment]
> > 我执行“ python start.py 105568”但失败
> > 无法创建fifo ../image_9050/user_cpu_state 
> > [+]发送缓冲区大小3158 
> > ./afl-fuzz -m none -t 800000+ -Q -i ./inputs -o。 / outputs -x关键字
> > afl-fuzz 2.52b by [lcamt​​uf@google.com](mailto:lcamtuf@google.com) 
> > [+]您有1个CPU内核和0个可运行任务（利用率：0％）。
> > [ _]设置输出目录... [_ ]扫描'./inputs'... 
> > [+]没有自动生成的字典标记可重复使用。
> > [ _]为所有输入文件创建硬链接... [_ ]从“关键字”（级别0）加载额外的词典... 
> > [+]已加载115个额外的令牌，大小范围为4 B至126B。
> > [！]警告：某些令牌相对较大（126 B）-考虑修剪。
> > [_]正在验证目标二进制文件... [_ ]尝试使用'id：000000，orig：seed'...
> > 进行空运行... dry run：./ outputs / queue / id：000000，orig：seed 
> > [*]启动fork服务器。 ..
> > [-]嗯，看起来目标二进制文件已终止，然后我们才能完成
> > 与所注入代码的握手。
> > 模糊器中可能存在一个可怕的错误。戳[lcamt​​uf@coredump.cx](mailto:lcamtuf@coredump.cx)的故障排除提示。
> > [-]程序
> > 中止：叉式服务器握手失败位置：init_forkserver（），afl-fuzz.c：2253
> > 我应该怎么办？
> 
> 我也有同样的问题。你解决了吗

no, i have no idea to solve this problem sorry......

**Comment by pureGavin** [comment]
> > i do "python start.py 105568" but failed
> > Could not create fifo ../image_9050/user_cpu_state
> > [+] sending buffer size 3158
> > ./afl-fuzz -m none -t 800000+ -Q -i ./inputs -o ./outputs -x keywords
> > afl-fuzz 2.52b by [lcamtuf@google.com](mailto:lcamtuf@google.com)
> > [+] You have 1 CPU core and 0 runnable tasks (utilization: 0%).
> > [_] Setting up output directories... [_] Scanning './inputs'...
> > [+] No auto-generated dictionary tokens to reuse.
> > [_] Creating hard links for all input files... [_] Loading extra dictionary from 'keywords' (level 0)...
> > [+] Loaded 115 extra tokens, size range 4 B to 126 B.
> > [!] WARNING: Some tokens are relatively large (126 B) - consider trimming.
> > [_] Validating target binary... [_] Attempting dry run with 'id:000000,orig:seed'...
> > dry run:./outputs/queue/id:000000,orig:seed
> > [*] Spinning up the fork server...
> > [-] Hmm, looks like the target binary terminated before we could complete a
> > handshake with the injected code. Perhaps there is a horrible bug in the
> > fuzzer. Poke [lcamtuf@coredump.cx](mailto:lcamtuf@coredump.cx) for troubleshooting tips.
> > [-] PROGRAM ABORT : Fork server handshake failed
> > Location : init_forkserver(), afl-fuzz.c:2253
> > what should i do?
> 
> I have the same problem. Have you solved it

do you have any good idea? maybe we can solve it together :p

**Comment by gy-cmykl** [comment]
Not at the moment. I installed it for the first time.
I tried to recompile, or I didn't solve it. I don't know where the problem is





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zyw-200/FirmAFL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月22日(星期四) 上午10:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zyw-200/FirmAFL] Fork server handshake failed (#43)





   
i do "python start.py 105568" but failed
 Could not create fifo ../image_9050/user_cpu_state
 [+] sending buffer size 3158
 ./afl-fuzz -m none -t 800000+ -Q -i ./inputs -o ./outputs -x keywords
 afl-fuzz 2.52b by ***@***.***
 [+] You have 1 CPU core and 0 runnable tasks (utilization: 0%).
 [] Setting up output directories... [] Scanning './inputs'...
 [+] No auto-generated dictionary tokens to reuse.
 [] Creating hard links for all input files... [] Loading extra dictionary from 'keywords' (level 0)...
 [+] Loaded 115 extra tokens, size range 4 B to 126 B.
 [!] WARNING: Some tokens are relatively large (126 B) - consider trimming.
 [] Validating target binary... [] Attempting dry run with 'id:000000,orig:seed'...
 dry run:./outputs/queue/id:000000,orig:seed
 [*] Spinning up the fork server...
 [-] Hmm, looks like the target binary terminated before we could complete a
 handshake with the injected code. Perhaps there is a horrible bug in the
 fuzzer. Poke ***@***.*** for troubleshooting tips.
 [-] PROGRAM ABORT : Fork server handshake failed
 Location : init_forkserver(), afl-fuzz.c:2253
 what should i do?
  
I have the same problem. Have you solved it
  
do you have any good idea? maybe we can solve it together :p

**Comment by pureGavin** [comment]
> 现在不行。我是第一次安装它。我试图重新编译，或者我没有解决。我不知道问题出在哪里
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zyw-200/FirmAFL" ***@***.***&gt;; 发送时间:&nbsp;2021年4月22日(星期四) 上午10:42 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [zyw-200/FirmAFL] Fork server handshake failed (#43) i do "python start.py 105568" but failed Could not create fifo ../image_9050/user_cpu_state [+] sending buffer size 3158 ./afl-fuzz -m none -t 800000+ -Q -i ./inputs -o ./outputs -x keywords afl-fuzz 2.52b by ***@***.*** [+] You have 1 CPU core and 0 runnable tasks (utilization: 0%). [] Setting up output directories... [] Scanning './inputs'... [+] No auto-generated dictionary tokens to reuse. [] Creating hard links for all input files... [] Loading extra dictionary from 'keywords' (level 0)... [+] Loaded 115 extra tokens, size range 4 B to 126 B. [!] WARNING: Some tokens are relatively large (126 B) - consider trimming. [] Validating target binary... [] Attempting dry run with 'id:000000,orig:seed'... dry run:./outputs/queue/id:000000,orig:seed [*] Spinning up the fork server... [-] Hmm, looks like the target binary terminated before we could complete a handshake with the injected code. Perhaps there is a horrible bug in the fuzzer. Poke ***@***.*** for troubleshooting tips. [-] PROGRAM ABORT : Fork server handshake failed Location : init_forkserver(), afl-fuzz.c:2253 what should i do? I have the same problem. Have you solved it do you have any good idea? maybe we can solve it together :p — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

well... tell me if you have some idea, maybe i can help you :p

**Comment by gy-cmykl** [comment]
I try to learn from this“ ***@***.*** ”Email from email, but I didn't get a response.Do you have any good ideas?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zyw-200/FirmAFL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月22日(星期四) 下午4:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zyw-200/FirmAFL] Fork server handshake failed (#43)





  
现在不行。我是第一次安装它。我试图重新编译，或者我没有解决。我不知道问题出在哪里
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zyw-200/FirmAFL" @.&gt;; 发送时间:&nbsp;2021年4月22日(星期四) 上午10:42 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [zyw-200/FirmAFL] Fork server handshake failed (#43) i do "python start.py 105568" but failed Could not create fifo ../image_9050/user_cpu_state [+] sending buffer size 3158 ./afl-fuzz -m none -t 800000+ -Q -i ./inputs -o ./outputs -x keywords afl-fuzz 2.52b by @.*** [+] You have 1 CPU core and 0 runnable tasks (utilization: 0%). [] Setting up output directories... [] Scanning './inputs'... [+] No auto-generated dictionary tokens to reuse. [] Creating hard links for all input files... [] Loading extra dictionary from 'keywords' (level 0)... [+] Loaded 115 extra tokens, size range 4 B to 126 B. [!] WARNING: Some tokens are relatively large (126 B) - consider trimming. [] Validating target binary... [] Attempting dry run with 'id:000000,orig:seed'... dry run:./outputs/queue/id:000000,orig:seed [] Spinning up the fork server... [-] Hmm, looks like the target binary terminated before we could complete a handshake with the injected code. Perhaps there is a horrible bug in the fuzzer. Poke @.** for troubleshooting tips. [-] PROGRAM ABORT : Fork server handshake failed Location : init_forkserver(), afl-fuzz.c:2253 what should i do? I have the same problem. Have you solved it do you have any good idea? maybe we can solve it together :p — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
well... tell me if you have some idea, maybe i can help you :p
